// Code generated by logcopter-gen; DO NOT EDIT.

package templates

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.jesus.pkg.web.templates")
